import React from 'react';
import './TermsAndConditions.css';
import Marquee from '../Home/Marquee/Marquee';
import Header from '../Home/Header/Header';
import Footer from '../Home/Footer/Footer';

function TermsAndConditions() {
  return (
    <>
    <Marquee/>
    <Header/>
    <div className='tc-container'>
        <p className='tc-head'>Terms and Conditions</p><br></br>
        <p className='heading'>Welcome to TechHaven</p>
        <p className='para'>This document is an electronic record in terms of the Information Technology Act, 2000 and the amended provisions relating to electronic records in various statutes, and is generated by a computer system, not requiring any physical or digital signatures. This document is published in accordance with Rule 3 (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011, requiring the publication of rules, regulations, privacy policy, and Terms of Use for access to or usage of www.techhaven.com (hereinafter referred to as "Website").</p>
        <p className='para'>The website is owned by TechHaven Private Limited (hereinafter referred to as "Company"/"TechHaven"), a company incorporated under the Companies Act, 1956, with its registered office located at Sattur, Virudhunagar- 626 203.</p>
        <p className="small-heading">Terms & Conditions</p>
        <p className="para">In these Terms & Conditions, references to "you," "user" shall mean the end-user accessing the website, its content, and using the services offered through the website. "Service Providers" shall mean independent third-party service providers, and "we," "us," and "our" shall mean "TechHaven Private Limited," its affiliates, and partners.</p>
        <p className="para">By accessing our site and/or purchasing products from us, you engage in our "Service" and agree to be bound by the following Terms & Conditions, including those additional terms, conditions, and policies referenced herein or available by hyperlink. These Terms & Conditions apply to all users of the site, including browsers, vendors, customers, merchants, and contributors of content.</p>
        <p className="para">Please read these Terms & Conditions carefully before accessing or using the website. By accessing or using any part of the website, you agree to be bound by these Terms. If you do not agree to all the terms and conditions of this agreement, then you may not access the website or use any services. If these Terms & Conditions are considered an offer, acceptance is expressly limited to these Terms.</p>
        <p className="para">We reserve the right to update, change, or replace any part of these Terms & Conditions by posting updates or changes on the website. It is your responsibility to check this page periodically for changes. Your continued use of or access to the website following the posting of any changes constitutes acceptance of those changes.</p>
        <p className="small-heading">Online Store Terms</p>
        <p className="para">By agreeing to these Terms & Conditions, you represent that you are at least the age of majority in your state or province of residence or that you are the age of majority and have given us your consent to allow any of your minor dependents to use this site. You may not use our products for any illegal or unauthorized purpose, nor may you, in the use of the Service, violate any laws in India (including but not limited to copyright laws).</p>
        <p className="small-heading">General Conditions</p>
        <p className="para">We reserve the right to refuse service to anyone for any reason at any time. Your content (excluding payment details) may be transferred unencrypted across various networks and may undergo changes to conform to technical requirements. Payment details are always encrypted during transfer over networks.</p>
        <p className="para">You agree not to reproduce, duplicate, copy, sell, resell, or exploit any portion of the Service, use of the Service, or access to the Service or any contact on the website without express written permission from us.</p>
        <p className="small-heading">Accuracy, Completeness, and Timeliness of Information</p>
        <p className="para">We are not responsible for information on this site that may not be accurate, complete, or current. The material on this site is provided for general information purposes and should not be relied upon as the sole basis for decision-making without consulting more accurate, complete, or timely sources. Any reliance on material on this site is at your own risk.</p>
        <p className="small-heading">Modifications to the Service and Prices</p>
        <p className="para">Prices for our products are subject to change without notice. We reserve the right to modify or discontinue the Service (or any part thereof) at any time without notice.</p>
        <p className="small-heading">Products or Services</p>
        <p className="para">Certain products or services may be available exclusively online and may have limited quantities subject to our return policy. We reserve the right to limit sales of our products to any person, geographic region, or jurisdiction and may exercise this right on a case-by-case basis.</p>
        <p className="small-heading">Accuracy of Billing and Account Information</p>
        <p className="para">We reserve the right to refuse any order placed with us. We may limit or cancel quantities purchased per person, per household, or per order. In the event of changes to or cancellation of an order, we will attempt to notify you via the contact details provided at the time the order was made. You agree to provide current, complete, and accurate purchase and account information for all purchases made at our store.</p>
        <p className="small-heading">User Comments, Feedback, and Other Submissions</p>
        <p className="para">If you submit any creative ideas, suggestions, or feedback to us (collectively, 'comments'), you agree that we may, without restriction, edit, copy, publish, or use your comments. We are under no obligation to maintain any comments in confidence, pay compensation, or respond to any comments.</p>
        <p className="small-heading">Personal Information</p>
        <p className="para">Your submission of personal information is governed by our Privacy Policy. Please refer to the Privacy Policy for details.</p>
        <p className="small-heading">Errors, Inaccuracies, and Omissions</p>
        <p className="para">We reserve the right to correct any errors or omissions on the website, update information, or cancel orders if any information is inaccurate without prior notice (including after an order has been placed).</p>
        <p className="small-heading">Prohibited Uses</p>
        <p className="para">You are prohibited from using the website or its content for unlawful purposes, soliciting illegal acts, violating laws, or infringing on intellectual property rights, among other restrictions. We reserve the right to terminate your use of the Service for any prohibited use.</p>
        <p className="small-heading">Disclaimer of Warranties; Limitation of Liability</p>
        <p className="para">We do not guarantee that your use of the Service will be uninterrupted or error-free. You agree that your use of the Service is at your sole risk. The Service and all products delivered to you are provided "as is" without any warranties.</p>
        <p className="para">In no case shall TechHaven, its directors, employees, affiliates, or service providers be liable for any damages arising from your use of the Service or any products obtained through the Service.</p>
        <p className="para">By using this website, you agree to abide by these Terms & Conditions. For any further questions, please contact us at grievance@techhaven.com.</p>
    </div>
    <Footer/>
    </>
  )
}

export default TermsAndConditions