# Generated by Django 5.1 on 2024-08-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='type',
            new_name='laptop_type',
        ),
        migrations.AlterField(
            model_name='laptop',
            name='images',
            field=models.JSONField(default=list),
        ),
    ]
