# Generated by Django 5.1 on 2024-08-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_processor_laptop_cpu'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='touchscreen',
            field=models.BooleanField(default=False),
        ),
    ]
