# Generated by Django 5.1 on 2024-08-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_laptop_touchscreen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='description',
        ),
        migrations.AddField(
            model_name='laptop',
            name='description_para',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='laptop',
            name='description_points',
            field=models.TextField(default=''),
        ),
    ]
