# Generated by Django 5.1 on 2024-09-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_laptop_description_laptop_description_para_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description_para', models.TextField(default='')),
                ('description_points', models.TextField(default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('brand', models.CharField(max_length=255)),
                ('images', models.JSONField(default=list)),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('num_reviews', models.IntegerField(default=0)),
                ('dimensions', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('warranty', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('speaker_type', models.CharField(max_length=255)),
                ('power_output', models.CharField(blank=True, max_length=100, null=True)),
                ('connectivity', models.CharField(blank=True, max_length=255, null=True)),
                ('battery_life', models.CharField(blank=True, max_length=255, null=True)),
                ('frequency_response', models.CharField(blank=True, max_length=255, null=True)),
                ('waterproof', models.BooleanField(default=False)),
                ('smart_assistant', models.CharField(blank=True, max_length=100, null=True)),
                ('microphone', models.BooleanField(default=False)),
                ('bass_boost', models.BooleanField(default=False)),
                ('led_lighting', models.BooleanField(default=False)),
                ('multi_device_pairing', models.BooleanField(default=False)),
                ('audio_inputs', models.CharField(blank=True, max_length=255, null=True)),
                ('driver_size', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
