# Generated by Django 5.1 on 2024-09-15 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_headphoneearbuds'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HeadphoneEarbuds',
            new_name='HpEb',
        ),
    ]
