# Generated by Django 5.1 on 2024-09-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_hpeb_charging_case_dimensions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedTv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description_para', models.TextField(default='')),
                ('description_points', models.TextField(default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('brand', models.CharField(max_length=255)),
                ('images', models.JSONField(default=list)),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('num_reviews', models.IntegerField(default=0)),
                ('dimensions', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('warranty', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('tv_type', models.CharField(max_length=255)),
                ('screen_size', models.CharField(max_length=10)),
                ('display_technology', models.CharField(blank=True, max_length=50, null=True)),
                ('resolution', models.CharField(max_length=50)),
                ('hdr_support', models.BooleanField(default=False)),
                ('refresh_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('smart_tv_features', models.TextField(blank=True, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=50, null=True)),
                ('audio_output', models.CharField(blank=True, max_length=100, null=True)),
                ('dolby_atmos', models.BooleanField(default=False)),
                ('hdmi_ports', models.IntegerField(blank=True, null=True)),
                ('usb_ports', models.IntegerField(blank=True, null=True)),
                ('bluetooth_version', models.CharField(blank=True, max_length=10, null=True)),
                ('wifi_support', models.BooleanField(default=False)),
                ('wifi_version', models.CharField(blank=True, max_length=10, null=True)),
                ('ethernet_port', models.BooleanField(default=False)),
                ('vesa_mount', models.CharField(blank=True, max_length=50, null=True)),
                ('energy_efficiency_rating', models.CharField(blank=True, max_length=10, null=True)),
                ('contrast_ratio', models.CharField(blank=True, max_length=50, null=True)),
                ('viewing_angles', models.CharField(blank=True, max_length=50, null=True)),
                ('panel_type', models.CharField(blank=True, max_length=50, null=True)),
                ('upscaling_technology', models.CharField(blank=True, max_length=100, null=True)),
                ('streaming_services', models.TextField(blank=True, null=True)),
                ('vrr_support', models.BooleanField(default=False)),
                ('allm_support', models.BooleanField(default=False)),
                ('bezel_size', models.CharField(blank=True, max_length=50, null=True)),
                ('power_consumption', models.CharField(blank=True, max_length=100, null=True)),
                ('standby_power_consumption', models.CharField(blank=True, max_length=50, null=True)),
                ('backlight_type', models.CharField(blank=True, max_length=100, null=True)),
                ('color_gamut', models.CharField(blank=True, max_length=100, null=True)),
                ('voice_assistant', models.CharField(blank=True, max_length=100, null=True)),
                ('included_accessories', models.TextField(blank=True, null=True)),
                ('led_type', models.CharField(blank=True, max_length=50, null=True)),
                ('screen_curvature', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
