# Generated by Django 5.1 on 2024-09-17 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_ledtv_smart_tv_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledtv',
            name='contrast_ratio',
        ),
        migrations.RemoveField(
            model_name='ledtv',
            name='viewing_angles',
        ),
    ]
