# Generated by Django 5.1 on 2024-09-17 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_ledtv_contrast_ratio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledtv',
            name='color_gamut',
        ),
    ]
