# Generated by Django 5.1 on 2024-09-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_ledtv_color_gamut'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedProjector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description_para', models.TextField(default='')),
                ('description_points', models.TextField(default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('brand', models.CharField(max_length=255)),
                ('images', models.JSONField(default=list)),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('num_reviews', models.IntegerField(default=0)),
                ('dimensions', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('warranty', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('projector_type', models.CharField(max_length=100)),
                ('native_resolution', models.CharField(max_length=50)),
                ('brightness', models.IntegerField()),
                ('contrast_ratio', models.CharField(blank=True, max_length=50, null=True)),
                ('throw_distance', models.CharField(blank=True, max_length=50, null=True)),
                ('projection_size', models.CharField(blank=True, max_length=50, null=True)),
                ('lamp_life', models.IntegerField(blank=True, null=True)),
                ('aspect_ratio', models.CharField(blank=True, max_length=20, null=True)),
                ('zoom', models.CharField(blank=True, max_length=50, null=True)),
                ('lens_shift', models.BooleanField(default=False)),
                ('keystone_correction', models.BooleanField(default=False)),
                ('input_ports', models.CharField(blank=True, max_length=255, null=True)),
                ('wireless_connectivity', models.CharField(blank=True, max_length=255, null=True)),
                ('speaker_output', models.CharField(blank=True, max_length=50, null=True)),
                ('three_d_support', models.BooleanField(default=False)),
                ('remote_control', models.BooleanField(default=False)),
                ('included_accessories', models.TextField(blank=True, null=True)),
                ('projection_technology', models.CharField(blank=True, max_length=50, null=True)),
                ('hdr_support', models.BooleanField(default=False)),
                ('noise_level', models.CharField(blank=True, max_length=20, null=True)),
                ('power_consumption', models.CharField(blank=True, max_length=100, null=True)),
                ('projection_ratio', models.CharField(blank=True, max_length=50, null=True)),
                ('focus_type', models.CharField(blank=True, max_length=50, null=True)),
                ('bluetooth_audio', models.BooleanField(default=False)),
                ('smart_features', models.BooleanField(default=False)),
                ('frame_interpolation', models.BooleanField(default=False)),
                ('battery_life', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
