# Generated by Django 5.1 on 2024-09-18 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_ledprojector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledprojector',
            name='battery_life',
        ),
        migrations.RemoveField(
            model_name='ledprojector',
            name='frame_interpolation',
        ),
    ]
