# Generated by Django 5.1 on 2024-09-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_remove_ledprojector_battery_life_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Microphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description_para', models.TextField(default='')),
                ('description_points', models.TextField(default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('brand', models.CharField(max_length=255)),
                ('images', models.JSONField(default=list)),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('num_reviews', models.IntegerField(default=0)),
                ('dimensions', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('warranty', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('microphone_type', models.CharField(max_length=255)),
                ('connectivity', models.CharField(blank=True, max_length=255, null=True)),
                ('frequency_response', models.CharField(blank=True, max_length=255, null=True)),
                ('sensitivity', models.CharField(blank=True, max_length=100, null=True)),
                ('impedance', models.CharField(blank=True, max_length=100, null=True)),
                ('polar_pattern', models.CharField(blank=True, max_length=100, null=True)),
                ('diaphragm_size', models.CharField(blank=True, max_length=100, null=True)),
                ('signal_to_noise_ratio', models.CharField(blank=True, max_length=100, null=True)),
                ('max_spl', models.CharField(blank=True, max_length=100, null=True)),
                ('pad_switch', models.BooleanField(default=False)),
                ('low_cut_filter', models.BooleanField(default=False)),
                ('shock_mount_included', models.BooleanField(default=False)),
                ('pop_filter_included', models.BooleanField(default=False)),
                ('phantom_power_required', models.BooleanField(default=False)),
                ('wireless_connectivity', models.BooleanField(default=False)),
                ('audio_sample_rate', models.CharField(blank=True, max_length=100, null=True)),
                ('mounting_options', models.CharField(blank=True, max_length=255, null=True)),
                ('included_accessories', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
