# Generated by Django 5.1 on 2024-09-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_microphone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description_para', models.TextField(default='')),
                ('description_points', models.TextField(default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('brand', models.CharField(max_length=255)),
                ('images', models.JSONField(default=list)),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('num_reviews', models.IntegerField(default=0)),
                ('dimensions', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('warranty', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('accessory_category', models.CharField(max_length=255)),
                ('storage_capacity', models.CharField(max_length=255)),
                ('interface_type', models.CharField(blank=True, max_length=255, null=True)),
                ('form_factor', models.CharField(blank=True, max_length=100, null=True)),
                ('read_speed', models.CharField(blank=True, max_length=100, null=True)),
                ('write_speed', models.CharField(blank=True, max_length=100, null=True)),
                ('rpm', models.IntegerField(blank=True, null=True)),
                ('cache_size', models.CharField(blank=True, max_length=100, null=True)),
                ('fan_speed', models.CharField(blank=True, max_length=100, null=True)),
                ('airflow', models.CharField(blank=True, max_length=100, null=True)),
                ('noise_level', models.CharField(blank=True, max_length=100, null=True)),
                ('bearing_type', models.CharField(blank=True, max_length=100, null=True)),
                ('fan_size', models.CharField(blank=True, max_length=100, null=True)),
                ('gpu_chipset', models.CharField(max_length=255)),
                ('memory_size', models.CharField(blank=True, max_length=255, null=True)),
                ('memory_type', models.CharField(blank=True, max_length=100, null=True)),
                ('core_clock', models.CharField(blank=True, max_length=100, null=True)),
                ('boost_clock', models.CharField(blank=True, max_length=100, null=True)),
                ('power_consumption', models.CharField(blank=True, max_length=100, null=True)),
                ('audio_channels', models.CharField(blank=True, max_length=100, null=True)),
                ('signal_to_noise_ratio', models.CharField(blank=True, max_length=100, null=True)),
                ('sample_rate', models.CharField(blank=True, max_length=100, null=True)),
                ('audio_processor', models.CharField(blank=True, max_length=255, null=True)),
                ('output_ports', models.CharField(blank=True, max_length=255, null=True)),
                ('input_ports', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_ports', models.IntegerField(blank=True, null=True)),
                ('usb_version', models.CharField(blank=True, max_length=50, null=True)),
                ('interface', models.CharField(blank=True, max_length=50, null=True)),
                ('data_transfer_rate', models.CharField(blank=True, max_length=100, null=True)),
                ('power_output_per_port', models.CharField(blank=True, max_length=100, null=True)),
                ('chipset', models.CharField(blank=True, max_length=255, null=True)),
                ('socket_type', models.CharField(blank=True, max_length=100, null=True)),
                ('ram_slots', models.IntegerField(blank=True, null=True)),
                ('max_ram_capacity', models.CharField(blank=True, max_length=100, null=True)),
                ('storage_ports', models.CharField(blank=True, max_length=255, null=True)),
                ('expansion_slots', models.CharField(blank=True, max_length=255, null=True)),
                ('usb_ports', models.CharField(blank=True, max_length=255, null=True)),
                ('network_ports', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
