# Generated by Django 5.1 on 2024-09-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_computeraccessories'),
    ]

    operations = [
        migrations.AddField(
            model_name='computeraccessories',
            name='included_items',
            field=models.TextField(blank=True, null=True),
        ),
    ]
