# Generated by Django 5.1 on 2024-09-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_computeraccessories_included_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computeraccessories',
            name='gpu_chipset',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
