# Generated by Django 5.1 on 2024-09-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_computeraccessories_storage_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='computeraccessories',
            name='gpu_fan_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='computeraccessories',
            name='gpu_fan_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
