# Generated by Django 5.1 on 2024-09-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_computeraccessories_gpu_fan_included_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description_para', models.TextField(default='')),
                ('description_points', models.TextField(default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('brand', models.CharField(max_length=255)),
                ('images', models.JSONField(default=list)),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('num_reviews', models.IntegerField(default=0)),
                ('dimensions', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('warranty', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('accessory_category', models.CharField(max_length=255)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('adjustable_height', models.BooleanField(default=False)),
                ('cooling_feature', models.BooleanField(default=False)),
                ('weight_capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fan_speed', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_fans', models.IntegerField(blank=True, null=True)),
                ('led_lighting', models.BooleanField(default=False)),
                ('noise_level', models.CharField(blank=True, max_length=100, null=True)),
                ('water_resistant', models.BooleanField(default=False)),
                ('compatibility', models.CharField(blank=True, max_length=255, null=True)),
                ('ports', models.CharField(blank=True, max_length=255, null=True)),
                ('power_delivery', models.BooleanField(default=False)),
                ('compatible_devices', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_ports', models.IntegerField(blank=True, null=True)),
                ('usb_version', models.CharField(blank=True, max_length=50, null=True)),
                ('capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('output_ports', models.IntegerField(blank=True, null=True)),
                ('fast_charging', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
