# Generated by Django 5.1 on 2024-09-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_laptopaccessories_max_adjustable_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptopaccessories',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='laptopaccessories',
            name='compatibility',
        ),
        migrations.AddField(
            model_name='laptopaccessories',
            name='included_items',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laptopaccessories',
            name='input_ports',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='laptopaccessories',
            name='output_ports',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
