# Generated by Django 5.1 on 2024-09-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_barcodescanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description_para', models.TextField(default='')),
                ('description_points', models.TextField(default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('brand', models.CharField(max_length=255)),
                ('images', models.JSONField(default=list)),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('num_reviews', models.IntegerField(default=0)),
                ('dimensions', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('warranty', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('accessory_category', models.CharField(max_length=255)),
                ('holder_type', models.CharField(blank=True, max_length=255, null=True)),
                ('mounting_mechanism', models.CharField(blank=True, max_length=255, null=True)),
                ('rotation', models.CharField(blank=True, max_length=255, null=True)),
                ('material', models.CharField(blank=True, max_length=255, null=True)),
                ('adjustable_height', models.BooleanField(default=False)),
                ('max_adjustable_height', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('foldable', models.BooleanField(default=False)),
                ('clamp_size', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('compatible_devices', models.CharField(blank=True, max_length=255, null=True)),
                ('cable_type', models.CharField(blank=True, max_length=255, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_output', models.CharField(blank=True, max_length=255, null=True)),
                ('data_transfer_speed', models.CharField(blank=True, max_length=100, null=True)),
                ('connector_type', models.CharField(blank=True, max_length=255, null=True)),
                ('fast_charging', models.BooleanField(default=False)),
                ('durability_rating', models.CharField(blank=True, max_length=255, null=True)),
                ('usb_version', models.CharField(blank=True, max_length=100, null=True)),
                ('port_type', models.CharField(blank=True, max_length=255, null=True)),
                ('card_slots', models.CharField(blank=True, max_length=255, null=True)),
                ('kickstand_feature', models.BooleanField(default=False)),
                ('magnetic_closure', models.BooleanField(default=False)),
                ('rfid_protection', models.BooleanField(default=False)),
                ('belt_clip', models.BooleanField(default=False)),
                ('capacity', models.CharField(blank=True, max_length=255, null=True)),
                ('speed_class', models.CharField(blank=True, max_length=255, null=True)),
                ('read_speed', models.CharField(blank=True, max_length=100, null=True)),
                ('write_speed', models.CharField(blank=True, max_length=100, null=True)),
                ('form_factor', models.CharField(blank=True, max_length=255, null=True)),
                ('water_proof', models.BooleanField(default=False)),
                ('shock_proof', models.BooleanField(default=False)),
                ('xray_proof', models.BooleanField(default=False)),
                ('tip_type', models.CharField(blank=True, max_length=255, null=True)),
                ('pressure_sensitivity', models.CharField(blank=True, max_length=100, null=True)),
                ('palm_rejection_support', models.BooleanField(default=False)),
                ('battery_life', models.CharField(blank=True, max_length=100, null=True)),
                ('charging_method', models.CharField(blank=True, max_length=255, null=True)),
                ('tilt_sensitivity', models.BooleanField(default=False)),
                ('replaceable_tips', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='laptopaccessories',
            name='material',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
