# Generated by Django 5.1 on 2024-09-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_mobileaccessories_alter_laptopaccessories_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileaccessories',
            name='clamp_size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
