# Generated by Django 5.1 on 2024-09-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_mobileaccessories_included_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='HdmiAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description_para', models.TextField(default='')),
                ('description_points', models.TextField(default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('brand', models.CharField(max_length=255)),
                ('images', models.JSONField(default=list)),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('num_reviews', models.IntegerField(default=0)),
                ('dimensions', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('warranty', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('accessory_category', models.CharField(max_length=255)),
                ('cable_length', models.CharField(blank=True, max_length=100, null=True)),
                ('cable_type', models.CharField(blank=True, max_length=100, null=True)),
                ('connector_type', models.CharField(blank=True, max_length=100, null=True)),
                ('gold_plated_connectors', models.BooleanField(default=False)),
                ('shielding', models.CharField(blank=True, max_length=100, null=True)),
                ('ethernet_support', models.BooleanField(default=False)),
                ('adapter_type', models.CharField(max_length=100)),
                ('connector_type_input', models.CharField(blank=True, max_length=100, null=True)),
                ('connector_type_output', models.CharField(blank=True, max_length=100, null=True)),
                ('resolution_support', models.CharField(blank=True, max_length=100, null=True)),
                ('audio_support', models.BooleanField(default=False)),
                ('active_passive', models.CharField(blank=True, max_length=50, null=True)),
                ('power_required', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
