# Generated by Django 5.1 on 2024-09-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_hdmiaccessories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdmiaccessories',
            name='adapter_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
