# Generated by Django 5.1 on 2024-09-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_alter_hdmiaccessories_adapter_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description_para', models.TextField(default='')),
                ('description_points', models.TextField(default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('brand', models.CharField(max_length=255)),
                ('images', models.JSONField(default=list)),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('num_reviews', models.IntegerField(default=0)),
                ('dimensions', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('warranty', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('mouse_type', models.CharField(max_length=255)),
                ('cable_length', models.CharField(blank=True, max_length=100, null=True)),
                ('connectivity_type', models.CharField(blank=True, max_length=255, null=True)),
                ('dpi', models.IntegerField()),
                ('ergonomics', models.BooleanField(default=False)),
                ('no_of_buttons', models.IntegerField()),
                ('led_lighting', models.BooleanField(default=False)),
                ('motion_detection', models.CharField(blank=True, max_length=255, null=True)),
                ('wireless_range', models.CharField(blank=True, max_length=100, null=True)),
                ('battery_life', models.CharField(blank=True, max_length=100, null=True)),
                ('battery_type', models.CharField(blank=True, max_length=255, null=True)),
                ('connectivity', models.CharField(blank=True, max_length=255, null=True)),
                ('recharge_time', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
