# Generated by Django 5.1 on 2024-09-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_mouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouse',
            name='dpi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
