# Generated by Django 5.1 on 2024-09-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_alter_mouse_dpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouse',
            name='included_items',
            field=models.TextField(blank=True, null=True),
        ),
    ]
