# Generated by Django 5.1 on 2024-09-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_keyboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyboard',
            name='keyboard_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
