# Generated by Django 5.1 on 2024-09-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_keyboard_keyboard_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyboard',
            name='included_items',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='no_of_keys',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
