# Generated by Django 5.1 on 2024-09-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_keyboard_included_items_keyboard_no_of_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyboard',
            name='ergonomics',
            field=models.BooleanField(default=False),
        ),
    ]
