# Generated by Django 5.1 on 2024-09-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_keyboard_wireless_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyboard',
            name='noise_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='noise_reduction_percent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
