# Generated by Django 5.1 on 2024-09-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_keyboard_noise_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyboard',
            name='phone_holder',
            field=models.BooleanField(default=False),
        ),
    ]
