# Generated by Django 5.1 on 2024-09-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0043_keyboard_phone_holder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description_para', models.TextField(default='')),
                ('description_points', models.TextField(default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('brand', models.CharField(max_length=255)),
                ('images', models.JSONField(default=list)),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('num_reviews', models.IntegerField(default=0)),
                ('dimensions', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('warranty', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('peripherals_category', models.CharField(max_length=255)),
                ('monitor_type', models.CharField(max_length=255)),
                ('screen_size', models.CharField(max_length=100)),
                ('resolution', models.CharField(max_length=100)),
                ('refresh_rate', models.CharField(blank=True, max_length=100, null=True)),
                ('panel_type', models.CharField(blank=True, max_length=255, null=True)),
                ('brightness', models.CharField(blank=True, max_length=100, null=True)),
                ('contrast_ratio', models.CharField(blank=True, max_length=100, null=True)),
                ('response_time', models.CharField(blank=True, max_length=100, null=True)),
                ('connectivity_options', models.CharField(blank=True, max_length=255, null=True)),
                ('aspect_ratio', models.CharField(blank=True, max_length=100, null=True)),
                ('color_gamut', models.CharField(blank=True, max_length=255, null=True)),
                ('touch_support', models.BooleanField(default=False)),
                ('portability_features', models.TextField(blank=True, null=True)),
                ('curved_radius', models.CharField(blank=True, max_length=255, null=True)),
                ('vesa_mount_compatible', models.BooleanField(default=False)),
                ('included_items', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
