# Generated by Django 5.1 on 2024-09-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_monitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyboardMouseCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description_para', models.TextField(default='')),
                ('description_points', models.TextField(default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('brand', models.CharField(max_length=255)),
                ('images', models.JSONField(default=list)),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('num_reviews', models.IntegerField(default=0)),
                ('dimensions', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('warranty', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('keyboard_type', models.CharField(max_length=255)),
                ('no_of_keys', models.CharField(blank=True, max_length=255, null=True)),
                ('layout', models.CharField(blank=True, max_length=100, null=True)),
                ('key_switch_type', models.CharField(blank=True, max_length=100, null=True)),
                ('led_backlighting', models.BooleanField(default=False)),
                ('programmable_keys', models.BooleanField(default=False)),
                ('anti_ghosting', models.BooleanField(default=False)),
                ('media_controls', models.BooleanField(default=False)),
                ('ergonomics', models.BooleanField(default=False)),
                ('phone_holder', models.BooleanField(default=False)),
                ('cable_length', models.CharField(blank=True, max_length=100, null=True)),
                ('connection_type', models.CharField(blank=True, max_length=50, null=True)),
                ('wireless_connectivity', models.CharField(blank=True, max_length=100, null=True)),
                ('wireless_range', models.CharField(blank=True, max_length=100, null=True)),
                ('battery_life', models.CharField(blank=True, max_length=100, null=True)),
                ('recharge_time', models.CharField(blank=True, max_length=100, null=True)),
                ('battery_type', models.CharField(blank=True, max_length=50, null=True)),
                ('keyboard_dimension', models.CharField(blank=True, max_length=255, null=True)),
                ('keyboard_weight', models.CharField(blank=True, max_length=255, null=True)),
                ('mouse_type', models.CharField(max_length=255)),
                ('mouse_cable_length', models.CharField(blank=True, max_length=100, null=True)),
                ('mouse_connectivity_type', models.CharField(blank=True, max_length=255, null=True)),
                ('dpi', models.CharField(blank=True, max_length=255, null=True)),
                ('no_of_buttons', models.IntegerField()),
                ('mouse_ergonomics', models.BooleanField(default=False)),
                ('mouse_led_backlighting', models.BooleanField(default=False)),
                ('motion_detection', models.CharField(blank=True, max_length=255, null=True)),
                ('mouse_wireless_range', models.CharField(blank=True, max_length=100, null=True)),
                ('mouse_battery_life', models.CharField(blank=True, max_length=100, null=True)),
                ('mouse_battery_type', models.CharField(blank=True, max_length=255, null=True)),
                ('mouse_connectivity', models.CharField(blank=True, max_length=255, null=True)),
                ('mouse_recharge_time', models.CharField(blank=True, max_length=100, null=True)),
                ('mouse_dimension', models.CharField(blank=True, max_length=255, null=True)),
                ('mouse_weight', models.CharField(blank=True, max_length=255, null=True)),
                ('included_items', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
