# Generated by Django 5.1 on 2024-09-28 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0045_keyboardmousecombo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyboardmousecombo',
            old_name='mouse_connectivity',
            new_name='mouse_connection_type',
        ),
        migrations.RenameField(
            model_name='keyboardmousecombo',
            old_name='mouse_connectivity_type',
            new_name='mouse_wireless_connectivity',
        ),
    ]
