# Generated by Django 5.1 on 2024-09-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0046_rename_mouse_connectivity_keyboardmousecombo_mouse_connection_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyboardmousecombo',
            name='mouse_usb_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='keyboardmousecombo',
            name='usb_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
