# Generated by Django 5.1 on 2024-09-28 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0047_keyboardmousecombo_mouse_usb_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyboardmousecombo',
            name='anti_ghosting',
        ),
    ]
