# Generated by Django 5.1 on 2024-09-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_hometheater'),
    ]

    operations = [
        migrations.AddField(
            model_name='hometheater',
            name='included_items',
            field=models.TextField(blank=True, null=True),
        ),
    ]
