# Generated by Django 5.1 on 2024-09-30 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0050_hometheater_included_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartLighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description_para', models.TextField(default='')),
                ('description_points', models.TextField(default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('brand', models.CharField(max_length=255)),
                ('images', models.JSONField(default=list)),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('num_reviews', models.IntegerField(default=0)),
                ('dimensions', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('warranty', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('power_consumption', models.CharField(max_length=100)),
                ('luminous_flux', models.CharField(blank=True, max_length=255, null=True)),
                ('color_temperature', models.CharField(blank=True, max_length=255, null=True)),
                ('bulb_type', models.CharField(blank=True, max_length=255, null=True)),
                ('connectivity', models.CharField(blank=True, max_length=255, null=True)),
                ('compatibility', models.CharField(blank=True, max_length=255, null=True)),
                ('smart_features', models.TextField(blank=True, null=True)),
                ('dimmable', models.BooleanField(default=False)),
                ('color_changing', models.BooleanField(default=False)),
                ('total_colors', models.CharField(blank=True, max_length=255, null=True)),
                ('voltage', models.CharField(blank=True, max_length=100, null=True)),
                ('lifespan', models.CharField(blank=True, max_length=100, null=True)),
                ('base_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
