# Generated by Django 5.1 on 2024-09-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0051_smartlighting'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCTVCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description_para', models.TextField(default='')),
                ('description_points', models.TextField(default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('brand', models.CharField(max_length=255)),
                ('images', models.JSONField(default=list)),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('num_reviews', models.IntegerField(default=0)),
                ('dimensions', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.CharField(blank=True, max_length=255, null=True)),
                ('warranty', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('resolution', models.CharField(blank=True, max_length=100, null=True)),
                ('field_of_view', models.CharField(blank=True, max_length=100, null=True)),
                ('night_vision', models.BooleanField(default=False)),
                ('connectivity', models.CharField(blank=True, max_length=255, null=True)),
                ('storage_type', models.CharField(blank=True, max_length=255, null=True)),
                ('power_supply', models.CharField(blank=True, max_length=255, null=True)),
                ('motion_detection', models.BooleanField(default=False)),
                ('two_way_audio', models.BooleanField(default=False)),
                ('weatherproof_rating', models.CharField(blank=True, max_length=100, null=True)),
                ('installation_type', models.CharField(blank=True, max_length=255, null=True)),
                ('included_items', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='barcodescanner',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='computeraccessories',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hdmiaccessories',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hometheater',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hpeb',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='keyboardmousecombo',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='laptopaccessories',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ledprojector',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ledtv',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='microphone',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mobileaccessories',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smartlighting',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
