# Generated by Django 5.1 on 2024-09-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0052_cctvcamera_alter_barcodescanner_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cctvcamera',
            name='loop_recording',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cctvcamera',
            name='material',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cctvcamera',
            name='sensor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
