# Generated by Django 5.1 on 2024-10-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0055_smartwatch_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='cctvcamera',
            name='product_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hometheater',
            name='product_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smartlighting',
            name='product_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smartwatch',
            name='product_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
