# Generated by Django 5.1 on 2024-10-01 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('support_type', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('language', models.TextField()),
            ],
        ),
    ]
